### ISSUE TITLE
Rebuild for Apple Silicon?

### ISSUE THREAD

**Issue by axu2** [wanadev/mozjpeg-lossless-optimization#5]
When I try to `import mozjpeg_lossless_optimization`

I get

```
ImportError: dlopen(/Users/name/Documents/GitHub/kcc/venv/lib/python3.9/site-packages/mozjpeg_lossless_optimization/_mozjpeg_opti.abi3.so, 0x0002): 
symbol not found in flat namespace '_jpeg_copy_critical_parameters'
```

Can anyone else replicate this? I feel like it probably just needs to be rebuilt and put on pip. I suspect that it is an Apple Silicon issue.

EDIT: for future reader, there's an issue with the arm version of the library on pip. For now install it from source. 

```
brew install cmake
pip uninstall mozjpeg-lossless-optimization
pip install https://files.pythonhosted.org/packages/62/cb/d73282f2e85058ceeb1dd19f4251ec7d47c05cff4b14d6b51e34a4f96c9e/mozjpeg-lossless-optimization-1.1.2.tar.gz
```

**Comment by flozz** [comment]
Hello,

Sadly I have no macOS device to debug this...

Maybe removing the `universal2` target for macOS could fix the issue (keeping only x86_64 and arm64)? 

https://github.com/wanadev/mozjpeg-lossless-optimization/blob/master/.github/workflows/python-packages.yml#LL60C42-L60C52

**Comment by flozz** [comment]
Can you try to install the `arm64` wheel corresponding to your Python version to check if it works better than the `universal2` one?

https://pypi.org/project/mozjpeg-lossless-optimization/#files

![image](https://github.com/wanadev/mozjpeg-lossless-optimization/assets/971438/3810cd8a-204a-4742-8624-396559149053)

**Comment by axu2** [comment]
I'm definitely using the arm64 version:

```
(venv) alex@mac-mini kcc % pip install mozjpeg_lossless_optimization
Collecting mozjpeg_lossless_optimization
  Using cached mozjpeg_lossless_optimization-1.1.2-cp311-cp311-macosx_11_0_arm64.whl (10.0 kB)
Requirement already satisfied: cffi>=1.0.0 in ./venv/lib/python3.11/site-packages (from mozjpeg_lossless_optimization) (1.15.1)
Requirement already satisfied: pycparser in ./venv/lib/python3.11/site-packages (from cffi>=1.0.0->mozjpeg_lossless_optimization) (2.21)
Installing collected packages: mozjpeg_lossless_optimization
Successfully installed mozjpeg_lossless_optimization-1.1.2

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
(venv) alex@mac-mini kcc % python
Python 3.11.3 (v3.11.3:f3909b8bc8, Apr  4 2023, 20:12:10) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mozjpeg_lossless_optimization
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alex/Documents/GitHub/kcc/venv/lib/python3.11/site-packages/mozjpeg_lossless_optimization/__init__.py", line 1, in <module>
    from .mozjpeg_opti import optimize
  File "/Users/alex/Documents/GitHub/kcc/venv/lib/python3.11/site-packages/mozjpeg_lossless_optimization/mozjpeg_opti.py", line 1, in <module>
    from ._mozjpeg_opti import lib, ffi
ImportError: dlopen(/Users/alex/Documents/GitHub/kcc/venv/lib/python3.11/site-packages/mozjpeg_lossless_optimization/_mozjpeg_opti.abi3.so, 0x0002): symbol not found in flat namespace '_jpeg_CreateCompress'
```

**Comment by axu2** [comment]
Mind telling me the exact commands I need? I've only ever installed stuff from pip.

**Comment by flozz** [comment]
Yes of course! :)

You can install it with the following command:

```
pip install https://files.pythonhosted.org/packages/62/cb/d73282f2e85058ceeb1dd19f4251ec7d47c05cff4b14d6b51e34a4f96c9e/mozjpeg-lossless-optimization-1.1.2.tar.gz
```

You will need build tools (cmake, and probably XCode on macOS?) and then everything should be automated :)

**Comment by axu2** [comment]
Works fine after installing cmake.
```
alex@mac-mini ~ % brew install cmake
Running `brew update --auto-update`...
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

Warning: Treating cmake as a formula. For the cask, use homebrew/cask/cmake
==> Fetching cmake
==> Downloading https://ghcr.io/v2/homebrew/core/cmake/manifests/3.26.4
######################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/cmake/blobs/sha256:68ab4f8a848b
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################### 100.0%
==> Pouring cmake--3.26.4.arm64_ventura.bottle.tar.gz
==> Caveats
To install the CMake documentation, run:
  brew install cmake-docs

Emacs Lisp files have been installed to:
  /opt/homebrew/share/emacs/site-lisp/cmake
==> Summary
🍺  /opt/homebrew/Cellar/cmake/3.26.4: 3,188 files, 45.5MB
==> Running `brew cleanup cmake`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

(venv) alex@mac-mini kcc % pip install https://files.pythonhosted.org/packages/62/cb/d73282f2e85058ceeb1dd19f4251ec7d47c05cff4b14d6b51e34a4f96c9e/mozjpeg-lossless-optimization-1.1.2.tar.gz
Collecting https://files.pythonhosted.org/packages/62/cb/d73282f2e85058ceeb1dd19f4251ec7d47c05cff4b14d6b51e34a4f96c9e/mozjpeg-lossless-optimization-1.1.2.tar.gz
  Using cached mozjpeg-lossless-optimization-1.1.2.tar.gz (1.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cffi>=1.0.0 in ./venv/lib/python3.11/site-packages (from mozjpeg-lossless-optimization==1.1.2) (1.15.1)
Requirement already satisfied: pycparser in ./venv/lib/python3.11/site-packages (from cffi>=1.0.0->mozjpeg-lossless-optimization==1.1.2) (2.21)
Building wheels for collected packages: mozjpeg-lossless-optimization
  Building wheel for mozjpeg-lossless-optimization (pyproject.toml) ... done
  Created wheel for mozjpeg-lossless-optimization: filename=mozjpeg_lossless_optimization-1.1.2-cp311-cp311-macosx_10_9_universal2.whl size=91411 sha256=b113af7ae2388489159ba61f0c7b1176ead8302d623e6cad02e47dabf6b3686a
  Stored in directory: /Users/alex/Library/Caches/pip/wheels/82/2f/4f/55e19af8e91176d5244cae573c1168febe308f06be0b22dfbb
Successfully built mozjpeg-lossless-optimization
Installing collected packages: mozjpeg-lossless-optimization
Successfully installed mozjpeg-lossless-optimization-1.1.2

(venv) alex@mac-mini kcc % python
Python 3.11.3 (v3.11.3:f3909b8bc8, Apr  4 2023, 20:12:10) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mozjpeg_lossless_optimization
>>> 
```

**Comment by axu2** [comment]
OK, I got to be honest, I see to be having issues with some other Python JPEG thing from the mac port of Portal. Let me debug that too.

**Comment by axu2** [comment]
@flozz Do you think changing `macos-11` to `macos-latest` would help in the build file? Maybe a bug was fixed between 11 and 13.

**Comment by axu2** [comment]
Yea the m1 runners are in beta.

**Comment by axu2** [comment]
Actually, I uninstalled everything in homebrew, I had some jpeg related stuff installed.
I also uninstalled homebrew python.
Now it works. No clue why.

**Comment by flozz** [comment]
Ok, Good to know. :)

I hope not too many people will have this issue... I have no Mac to work on it anyway ^^'

**Comment by axu2** [comment]
Based on the discussion in the other issue, seems like it was a python version issue. The latest 3.11.4 works, homebrew or not.
